# ===================================================================
# APPLICATION PROPERTIES
#
# List of Common Application Properties: 
#   - http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# 
# ===================================================================
# EMBEDDED SERVER CONFIGURATION
# *** REVIEW https://www.predix.io/support/article/KB0011758 for server config settings
server:
  port: 8080
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto    
    protocol-header-https-value: http    
  session:
    cookie:
      http-only: true # only allows http requests not JavaScript
      secure: true # only sends via https            
      
# COMMON SPRING CONFIGURATION  
spring:  
  profiles:
    #active: predix-basic
    #active: predix-basic,local
    active: ge-oidc,local
    #active: ge-oidc
  resources:
    chain:
      enabled: true
  main:
    banner-mode: "off"    
    
# LOGGING
logging:  
  level:
    org.springframework.security: debug
    
# SECURITY (SecurityProperties)
security:
  ignored: /favicon.ico, /lib/**,/resources/**
  basic:
    enabled: false
    
---

spring:
  profiles: local

ge:
  network:
    proxy-host: proxy-src.research.ge.com
    proxy-port: 8080
    
security:  
  oauth2:               
    client:
      pre-established-redirect-uri: http://localhost:8080/login                    
      registered-redirect-uri: http://localhost:8080/login

server:
  session:
    cookie:
      secure: false   

logging:  
  level:
    org.springframework.security: trace     
---    
# ----------------------------------------------------------------------------------
# GE OIDC (Pingfederate) profile configuration
#
# Using Production OIDC Environment created using the self-service 
#    tool https://oidcapi.corporate.ge.com/
# Replace the clientId, and clientSecret with your application specific values
# Redirect URI is only needed if it doesn't include /login
# ----------------------------------------------------------------------------------
spring:
  profiles: ge-oidc  
      
# SECURITY OAUTH2 CLIENT (OAuth2ClientProperties)         
security:  
  oauth2:               
    client:
      clientId: gepw_uaa_ws
      clientSecret: gepwuaaws
      accessTokenUri: https://fssfed.ge.com/fss/as/token.oauth2
      userAuthorizationUri: https://fssfed.ge.com/fss/as/authorization.oauth2
      scope: openid,profile
      pre-established-redirect-uri: http://localhost:8080/login
      registered-redirect-uri: http://localhost:8080/login
      use-current-uri: false
      
# SECURITY OAUTH2 RESOURCES (ResourceServerProperties)            
    resource:
      userInfoUri: https://fssfed.ge.com/fss/idp/userinfo.openid
      prefer-token-info: true
                
---

# ----------------------------------------------------------------------------------
# Predix Basic Shared UAA configuration
#
# Using Predix Basic Shared UAA created using the self-service 
#   tool https://shared-uaa.run.aws-usw02-pr.ice.predix.io
# Replace the clientId and clientSecret with your application specific values
# pre-established-redirect-uri is only needed if you don't have /login in your redirect-uri
# ----------------------------------------------------------------------------------
spring:
  profiles: predix-basic
  resources:
    chain:
      enabled: true

# SECURITY OAUTH2 CLIENT (OAuth2ClientProperties)     
security:
  oauth2:
    client:
      client-id: smiley-plant-svs-uaa
      client-secret: kranthiGEUAA
      access-token-uri:  https://52d8d211-3773-4f70-8607-15e68e1486c6.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token 
      user-authorization-uri:  https://52d8d211-3773-4f70-8607-15e68e1486c6.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/authorize      
      scope: openid,profile
      pre-established-redirect-uri: http://localhost:8080/login
      registered-redirect-uri: http://localhost:8080/login
      use-current-uri: false      
      
# SECURITY OAUTH2 RESOURCES (ResourceServerProperties)     
    resource:            
      userInfoUri: https://52d8d211-3773-4f70-8607-15e68e1486c6.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo            
      prefer-token-info: true      
